name: torch_pyenv
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - tqdm
  - scikit-image
  - ipykernel
  - ipywidgets
  - ca-certificates
  - openssl
  - certifi
  - h5py
  - streamlit
  - ismrmrd-python
  - piq
  - joblib
  - seaborn
  - wandb
  - simpleitk
  - ninja
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - cuda-toolkit
  - nibabel
  - conda-forge::pytorch-msssim
  - conda-forge::easydict
  - ipdb
  - termcolor
  - tensorboard
  - visdom
  - trimesh
  - pyyaml
  - gdown
  - anaconda::scikit-learn
